### ISSUE TITLE
EvangelistAnalysisTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/open-source-evangelists#5]
`public function testWithUserWithVeryLowPublicRepos()
    {
        EvangelistAnalysis::analyse('andela-kerinoso');
    }`

There is no assertion for this test function. Please Fix!

**Comment by kola-er** [comment]
Yes, there isn't because exception is thrown in function `EvangelistAnalysis::analyse()` for username `'andela-kerinoso'`. And the test function `public function testWithUserWithVeryLowPublicRepos()` tests for exception rather than assertion. Username `'andela-kerinoso'` is a dummy username with public repos less than 5 on GitHub.

**Comment by unicodeveloper** [comment]
I just saw your `@expectedException` annotation, So if it doesn't throw an exception, the tests would complain. Nice!!!
