### ISSUE TITLE
EvangelistFetchTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/open-source-evangelists#6]
`public function testSupplyOfEmptyAndInvalidUsername($username)
    {
        EvangelistFetch::getNumOfPublicRepos($username);
    }`

You didn't write any assertion for this.Please Fix!

**Comment by kola-er** [comment]
Yes, I didn't. The entire tests in that test case are on function `EvangelistFetch::getNumOfPublicRepos($username);`. There are 6 set of $username possibilities in which 4 are GItHub-registered usernames and 2 are GitHub-unregistered usernames. The 2 unregistered ones are tested for in case the user of this package mistakenly supplies them; one is empty string and the other is not empty. So `public function testSupplyOfEmptyAndInvalidUsername($username) { EvangelistFetch::getNumOfPublicRepos($username); }` takes care of exceptions thrown by the 2 unregistered usernames. In the comment 

> - Test for throw of Exception if the supplied username is empty or invalid
> - @param        string $username Username of an individual to be searched for on GitHub
> - @dataProvider supplyInvalidUsername
> - @expectedException Exception

above `public function testSupplyOfEmptyAndInvalidUsername($username) { EvangelistFetch::getNumOfPublicRepos($username); }` expected exception is indicated rather than assertion.

**Comment by unicodeveloper** [comment]
Awesome Explanation!.. :+1:
